<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\APIDashboard.Domain\APIDashboard.Domain.csproj" />
    <ProjectReference Include="..\APIDashboard.Infrastructure\APIDashboard.Infrastructure.csproj" />
  </ItemGroup>

</Project>
